[options]
HoldPkg = pacman glibc
Architecture = auto
Color
CheckSpace
SigLevel = Never
LocalFileSigLevel = Optional
ParallelDownloads = 5

[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[fbl]
SigLevel = Never
Server = file:///home/nekokrub/fbl-iso/repo
